### PR TITLE
handle callback query, to avoid the "spinny" circle on official Teleg…

### PR DESCRIPTION
**Pull request by SpEcHiDe**
…ram Clients

### CODE REVIEW

**Comment by code-rgb** [comment]
fast af

**Comment by Vontus** [comment]
Hey, thank you for your PR!

I think this would lead to Telegram complaining for answering a callback query twice when it fails for some reason and enters the catch block. Maybe it is a better idea to answer the query right at the end of the try block.

**Comment by SpEcHiDe** [comment]
Hi, 
I noticed that in the catch block, it is also showing a text, 
That's why I added answerCallbackQuery in the try block too, 
Should / can I move the text to a variable and use it only once outside the catch block?

**Comment by Vontus** [comment]
Yes, that'd be a good solution too.

**Pull request merged**
